name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    - name: Set deploy path
      run: echo "DEPLOYPATH=/home/crumanjr/public_html/" >> $GITHUB_ENV

    - name: Copy files
      run: /bin/cp -R Site/* $DEPLOYPATH